
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # blacklist
  except:
    - develop
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf false


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script: msbuild entrypoint.msbuild /t:build /v:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
# test_script:  msbuild entrypoint.msbuild /t:test /v:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing entire folder as a zip archive
  - path: 'build\logs'

  # pushing all *.nupkg files in build directory recursively
  - path: 'build\deploy\*.zip'


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off
